[package]
name = "loopback"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shared = { path = "../shared" }
quanta = "0.12"
rdma-sys = "0.3.0"
uninit = "0.6.2"
