server_ip := "192.168.2.1"
port := "12873"

executable := "rdma_ring_buffer_rust"

alias s := server
alias c := client

alias gc := git-commit
alias qs := quick-server

git_update:
	git pull

build: git_update
	cargo build

server: build
	./target/debug/{{executable}} --port {{port}} -g 1

client: build
	./target/debug/{{executable}} -s {{server_ip}} --port {{port}} -g 1

git-commit message="update":
	git add .
	git commit -am "{{message}}"
	git push

quick-server: git-commit server